### ISSUE TITLE
Rating Issue

### ISSUE THREAD

**Issue by TsinJu** [jmxd/Kometa#15]
Not sure why, but why is 5.7 red and 5.4 yellow? Surely the other way around would make more sense?
![Screenshot 2025-01-14 145453](https://github.com/user-attachments/assets/166b36bd-b05b-4526-a0e5-daac78796831)

Here's the Code for mass rating update

```
    operations:
      mass_originally_available_update: 
      - tmdb
      - tvdb
      mass_critic_rating_update:
      - imdb
      - tmdb
      mass_audience_rating_update: mdb_tmdb
      mass_content_rating_update:
      - mdb_commonsense
      - mdb_age_rating
      - omdb
      - NR
      mass_imdb_parental_labels: none
```
