### ISSUE TITLE
How to I install this?

### ISSUE THREAD

**Issue by IllMethods** [jmxd/Kometa#24]
Sorry, Kometa novice.

I have Kometa installed but I currently only use it for collections.

I am running it on unraid. Where do I put the files, and how do I put it into my config? Do I just put the overlays files in the overlays folder? Current overlays folder just has folders for each library followed by Original Posters.

Any help would be appreciated

**Comment by Rovey** [comment]
Place it in the overlays folder (create it if it doesn't exist) in /user/appdata/kometa/overlays. 
Your volume mapping (default) should be:

![Image](https://github.com/user-attachments/assets/8c09d287-8e7d-497c-8444-74ce38b0bd2a)

Then use:
```
libraries:
  Movies:
    library_name: Movies
    remove_overlays: false
    collection_files:
    - default: basic
    - default: imdb
    overlay_files:
    - file: config/overlays/media_info.yml
    - file: config/overlays/audience_rating.yml
    operations:
      mass_critic_rating_update: mdb_tomatoesaudience
```

If you run it manually from the console make sure you run it with app/kometa/kometa.py and don't run it from inside the app/kometa folder, that will ruin the paths when running it. Example:
`python3 app/kometa/kometa.py --overlays-only --ignore-schedules --run-library Movies`

![Image](https://github.com/user-attachments/assets/2ed48239-f03e-4779-abce-34f0505e0e2a)

![Image](https://github.com/user-attachments/assets/3a918c2a-181e-4f40-8d83-954f9ec15f3e)
